// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwyrxxjacogcioalhjge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3eXJ4eGphY29nY2lvYWxoamdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzU1NTQsImV4cCI6MjA2NDcxMTU1NH0.35VUs0GteXHm0Qw475-oFBxUr9XGPMttddtHoSw8BWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);